zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path: null # Or set a list of glob patterns, e.g. ["2026/survey/**","2026/reading-group/**"]

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: mail.cstnet.cn
  smtp_port: 994
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
  generation_kwargs:
    model: gpt-4o-mini

source:
  arxiv:
    # 除了计算机科学，补充了定量生物学(Quantitative Methods)和分子网络(Molecular Networks)
    category: ["cs.AI", "cs.CV", "cs.LG", "cs.CL", "q-bio.QM", "q-bio.MN"]
  biorxiv:
    # 启用 biorxiv 必须配置此项
    category: ["bioinformatics", "cancer biology", "genomics"]
  medrxiv:
    # 启用 medrxiv 必须配置此项
    category: ["oncology", "genetic and genomic medicine"]

executor:
  debug: ${oc.env:DEBUG,null}
  max_paper_num: 20
  source: ['arxiv','biorxiv','medrxiv']
